# This file is a bit of a special case as basalt isn't bootstrapped to use
# itself for installation. As a result, `shopt` options, env vars etc. are
# set in `./pkg/src/bin/basalt.sh` rather than this file. This file is
# still useful, though, since external tools can still parse this file
# to get meaningful information about the project

[package]
lang = "bash"
type = 'app'
name = 'basalt'
slug = 'basalt'
version = '0.10.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = 'The rock-solid Bash package manager'

[run]
dependencies = []
binDirs = ['bin']
sourceDirs = [
	'pkg/src/bin',
	'pkg/src/commands',
	'pkg/src/public',
	'pkg/src/util',
]
builtinDirs = []
completionDirs = ['pkg/completions']
manDirs = ['pkg/share/man']

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
