[package]
name = ''
slug = ''
version = ''
authors = []
description = ''

[run]
dependencies = []
sourceDirs = []
binDirs = []
completionDirs = []
manDirs = []

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
