[package]
name = 'basalt'
slug = 'basalt'
version = '0.9.0'
authors = ['Edwin Kofler <edwin@kofler.dev>']
description = ''

[run]
dependencies = []
sourceDirs = ['pkg/lib/cmd', 'pkg/lib/commands', 'pkg/lib/public', 'pkg/lib/util']
binDirs = ['pkg/bin']
completionDirs = []
manDirs = ['pkg/share/man']

[run.shellEnvironment]

[run.setOptions]

[run.shoptOptions]
