#!/usr/bin/env bash
# Transition layer between
source "$bin_path/basher-_util"
util.test_mock
command="$1"
shift

for f in "$bin_path"/subcmds/?*.sh; do
  source "$f"
done

set -e
shopt -s nullglob

source "basher-$command" "$@"
