name: CI

on:
  push:
    branches: [ main, fix-ci ]
  pull_request:
    branches: [ main, fix-ci ]

jobs:
  build-linux:
    strategy:
      matrix:
        bashver: ["4.3", "4.4", "5.0", "latest"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          wget --no-check-certificate -O bats.tar.gz https://github.com/bats-core/bats-core/archive/v1.3.0.tar.gz
          mkdir bats
          tar --strip-components=1 -xvzf bats.tar.gz -C bats

      - name: Build image
        run: |
          docker build --build-arg bashver=${{ matrix.bashver }} --tag bpm/bpm:bash-${{ matrix.bashver }} .
          docker run bash:${{ matrix.bashver }} --version

      - name: Run tests
        run: |
          time docker run bpm/bpm:bash-${{ matrix.bashver }} --tap /opt/bpm/tests

  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install dependencies
        run: |
          wget --no-check-certificate -O bats.tar.gz https://github.com/bats-core/bats-core/archive/v1.3.0.tar.gz
          mkdir bats
          tar --strip-components=1 -xvzf bats.tar.gz -C bats

          brew install bash coreutils

      - name: Run tests
        run: |
          bash --version
          git config --global user.email "user@example.com"
          git config --global user.name "User Name"
          time bats/bin/bats --tap tests
