name: 'ci'

on:
  push:
    branches: [main, dev, ci/*]
  pull_request:
    branches: [main, dev, ci/*]

permissions: read-all

# env:

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  test-linux:
    name: 'Linux Test'
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-20.04'] # ubuntu-18.04, ubuntu-20.04, ubuntu-latest
        bash-version: ['4.3', '4.4', '5.0', 'latest']

    runs-on: '${{ matrix.os }}'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Install Bats
        run: |
          subdir='.workflow-data'
          bats_version='1.4.1'

          curl -LsSo "$subdir/bats-core.tar.gz" --create-dirs \
            https://github.com/bats-core/bats-core/archive/v$bats_version.tar.gz
          tar --extract --transform "s,bats-core-$bats_version,bats-core," -C "$subdir" -f "$subdir/bats-core.tar.gz"

      - name: Build image
        run: |
          docker build \
            --build-arg bash_version=${{ matrix.bash-version }} \
            --tag basalt:bash-${{ matrix.bash-version }} \
            .

      - name: Run tests
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        run: |
          time docker run basalt:bash-${{ matrix.bash-version }} \
            --tap tests

  test-mac:
    name: 'MacOS Test'
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-10.15'] # macos-10.15, macos-11, macos-latest

    runs-on: '${{ matrix.os }}'

    steps:
      - uses: 'actions/checkout@v2'
        with:
          submodules: true
          path: 'source'

      - name: Install Prerequisites
        run: |
          # gnu-tar is only for the 'Install Bats' step
          brew install bash coreutils curl gnu-tar

      - name: Install Bats
        run: |
          subdir='.workflow-data'
          bats_version='1.4.1'

          cd source

          curl -LsSo "$subdir/bats-core.tar.gz" --create-dirs \
            https://github.com/bats-core/bats-core/archive/v$bats_version.tar.gz
          gtar --extract --transform "s,bats-core-$bats_version,bats-core," -C "$subdir" -f "$subdir/bats-core.tar.gz"

      - name: Run tests
        run: |
          subdir='.workflow-data'

          cd source

          bash --version
          git config --global user.email "user@example.com"
          git config --global user.name "User Name"
          printf "%s\n" "---"

          time "./$subdir/bats-core/bin/bats" --tap tests
